### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by jakjr** [Turini/estoque-laravel#1]
Olá,

este é o início dos códigos referentes ao livro sobre laravel ou o fim?

Porque estão faltando algumas coisa:
middlewares
form requests
commands
handlers/listeners
queues
..

Porque no arquivo routers.php não está sendo utilizado os verbs DELETE/PUT ?
Obrigado

**Comment by Turini** [comment]
Olá @jakjr, tudo bem? Você encontra exemplos de middlewares e form requests respectivamente em:

https://github.com/Turini/estoque-laravel/blob/master/app/Http/Middleware/AutorizacaoMiddleware.php
https://github.com/Turini/estoque-laravel/blob/master/app/Http/Requests/ProdutosRequest.php

Porém commands, listeners e queues não são cobertos nesse primeiro livro, que é uma introdução ao framework. Se quiser, você pode ver o sumário com todo conteúdo abordado em http://www.casadocodigo.com.br/pages/sumario-laravel-php. Grande abraço
